name = "template"
main = "./dist/worker.mjs"
account_id = "c63d756a160ad09cd9a82553c77e9174"
workers_dev = false
route = "edmund.dev/*"
compatibility_date = "2022-11-25"
compatibility_flags = ["streams_enable_constructors"]

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "CACHE"
id = "3e46a589dc17470a97cadf3fd8fcf07e"